AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image resizing service


Parameters:
  SourceBucketName:
    Type: String
  DestinationBucketName:
    Type: String


Resources:
  ## S3 bucket
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SourceBucketName
  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DestinationBucketName
      VersioningConfiguration:
        Status: Enabled

  FormatMediaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 1024

      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref SourceBucketName
        - S3FullAccessPolicy:
            BucketName: !Ref DestinationBucketName
      Environment:
        Variables:
          INPUT_BUCKET: !Ref SourceBucketName
          OUTPUT_BUCKET:  !Ref DestinationBucketName
      Layers:
        - 'arn:aws:lambda:us-east-1:643020469822:layer:ffmpeg:3'
        - 'arn:aws:lambda:us-east-1:643020469822:layer:PIL_layer:1'
      Events:
        S3CreateObject:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucket
            Events: s3:ObjectCreated:*



Outputs:
  SourceBucketName:
    Value: !Ref SourceBucketName
    Description: S3 source Bucket for media to be formatted
  DestinationBucketName:
    Value: !Ref DestinationBucketName
    Description: S3 destination Bucket for formatted media
